// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdEtpRyHvSUssNPJJlzI7QanmO0WYUY5c',
    appId: '1:813735532981:web:b60659ba1f86c818f961fc',
    messagingSenderId: '813735532981',
    projectId: 'bhojn-app',
    authDomain: 'bhojn-app.firebaseapp.com',
    storageBucket: 'bhojn-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCihYMgasbJjmXby6_HgsJuhXr6AuVXyVc',
    appId: '1:813735532981:android:1bfeb9ea3e2bf2b4f961fc',
    messagingSenderId: '813735532981',
    projectId: 'bhojn-app',
    storageBucket: 'bhojn-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA6Iz6bEN8nApnYyoeeywqaGwfn0mnPk0',
    appId: '1:813735532981:ios:1111452548d9a328f961fc',
    messagingSenderId: '813735532981',
    projectId: 'bhojn-app',
    storageBucket: 'bhojn-app.firebasestorage.app',
    iosBundleId: 'com.example.bhojnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA6Iz6bEN8nApnYyoeeywqaGwfn0mnPk0',
    appId: '1:813735532981:ios:1111452548d9a328f961fc',
    messagingSenderId: '813735532981',
    projectId: 'bhojn-app',
    storageBucket: 'bhojn-app.firebasestorage.app',
    iosBundleId: 'com.example.bhojnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdEtpRyHvSUssNPJJlzI7QanmO0WYUY5c',
    appId: '1:813735532981:web:56b6bc19baa8a3fdf961fc',
    messagingSenderId: '813735532981',
    projectId: 'bhojn-app',
    authDomain: 'bhojn-app.firebaseapp.com',
    storageBucket: 'bhojn-app.firebasestorage.app',
  );
}
